name: pulsedevice
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations:  # Flutter官方多語系支援
    sdk: flutter
  cached_network_image: ^3.4.1  # 圖片快取與異步加載
  flutter_svg: ^2.0.16  # 載入 SVG 向量圖片
  get: ^4.6.6  # GetX 狀態管理 / 路由跳轉 / DI
  shared_preferences: ^2.3.4  # 本地簡單儲存 (key-value儲存設定或登入資訊)
  connectivity_plus: ^6.1.1  # 網路連線狀態監聽 (Wi-Fi/4G/斷線)
  flutter_svg_provider: ^1.0.7  # 把 SVG 當 ImageProvider 使用
  pin_code_fields: ^8.0.1  # OTP驗證碼輸入格子UI
  sms_autofill: ^2.4.1  # SMS驗證碼自動讀取 (Android / iOS)
  responsive_grid_list: ^1.4.0  # 流式/自適應 Grid 排列
  qr_flutter: ^4.1.0  # 生成 QRCode 圖片
  mobile_scanner: ^7.0.0  # 手機相機掃描二維碼
  calendar_date_picker2: ^1.1.8  # 自訂版行事曆選日期
  fl_chart: ^0.70.0  # 畫圖表用的 (線圖、圓餅圖、柱狀圖)
  image_picker: ^1.1.2  # 開啟相機、選取相簿圖片
  permission_handler: ^11.0.1  # 權限請求與檢查 (相機、藍牙、儲存)
  flutter_blue_plus: ^1.35.5  # 藍牙掃描
  device_info_plus: ^11.4.0  # 取得裝置資訊 (機型/系統版本)
  flutter_spinkit: ^5.2.1  # 載入中動畫
  flutter_local_notifications: ^19.1.0  # 設定本地通知
  timezone: ^0.10.1  # 取得時區
  flutter_timezone: ^4.1.0  # 取得裝置時區
  # android_intent_plus: ^5.3.0  # Android 開啟其他應用程式
  path_provider: ^2.1.5  # 取得路徑
  path: ^1.9.1  # 路徑處理
  hive: ^2.2.3 # Hive資料庫
  hive_flutter: ^1.1.0 # Hive資料庫文件
  sqflite: ^2.4.2 # SQLite資料庫
  drift: ^2.26.1 # SQLite資料庫封裝
  drift_sqflite: ^2.0.1 # SQLite資料庫封裝
  dio: ^5.8.0+1 # 網路請求
  mime: ^2.0.0 # 檔案類型判別
  http_parser: ^4.1.2 # 檔案類型判別
  firebase_core: ^3.13.0 # Firebase
  firebase_messaging: ^15.2.5 # Firebase
  flutter_foreground_task: ^9.1.0 # 開啟前台服務
  background_fetch: ^1.3.8 # 開啟背景服務
  zxing2: ^0.2.4 # QRCode掃描
  
  yc_product_plugin:  # 藍牙設備連線操作 (第三方SDK，從Git拉取)
    git:
      url: https://gitee.com/yucheng_3/yc_product_plugin.git
      path: code/
      ref: 89962c165497ec484f1788b0d2546e1cc6a2f402
      
dev_dependencies: 
  flutter_test:  # Flutter內建單元測試
    sdk: flutter
  build_runner: ^2.4.15 # H資料生成器
  hive_generator: ^2.0.1 # Hive資料庫生成器
  drift_dev: ^2.26.0 # SQLite資料庫生成器
  flutter_launcher_icons: ^0.14.3 # Flutter應用程式圖標

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon.png"  # ← 你的 App Icon 路徑
  remove_alpha_ios: true

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400